// This file is generated by FlutterFire CLI.
// Run `flutterfire configure` after setting up your Firebase project to
// generate the real version of this file. The stub below allows the project
// to compile without the CLI output — replace it before running the app.
//
// Steps:
//   1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
//   2. Run: flutterfire configure
//   3. Select your Firebase project and the Android platform.
//   4. The real firebase_options.dart will be written here automatically.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // STUB VALUES — replace by running `flutterfire configure`
  // ─────────────────────────────────────────────────────────────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8EGARmdisJiTaZ-XLbxxrt52MowumhVQ',
    appId: '1:392159269720:android:00d448f391053246c24b2d',
    messagingSenderId: '392159269720',
    projectId: 'bitirme-b3e7a',
    storageBucket: 'bitirme-b3e7a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRr9iJPA2erICSUa7uNeshcgVMzdGt2IY',
    appId: '1:392159269720:ios:665cc8d40d42c846c24b2d',
    messagingSenderId: '392159269720',
    projectId: 'bitirme-b3e7a',
    storageBucket: 'bitirme-b3e7a.firebasestorage.app',
    iosBundleId: 'com.example.flutterTurkceOgrenmeApplication',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqHFZiqrDdmbV1W1KHLs49RnAiNrQdQ7U',
    appId: '1:392159269720:web:19717c2f30dc2e16c24b2d',
    messagingSenderId: '392159269720',
    projectId: 'bitirme-b3e7a',
    authDomain: 'bitirme-b3e7a.firebaseapp.com',
    storageBucket: 'bitirme-b3e7a.firebasestorage.app',
    measurementId: 'G-SPJKPBMMSX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRr9iJPA2erICSUa7uNeshcgVMzdGt2IY',
    appId: '1:392159269720:ios:665cc8d40d42c846c24b2d',
    messagingSenderId: '392159269720',
    projectId: 'bitirme-b3e7a',
    storageBucket: 'bitirme-b3e7a.firebasestorage.app',
    iosBundleId: 'com.example.flutterTurkceOgrenmeApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqHFZiqrDdmbV1W1KHLs49RnAiNrQdQ7U',
    appId: '1:392159269720:web:b44fa5eadbf69effc24b2d',
    messagingSenderId: '392159269720',
    projectId: 'bitirme-b3e7a',
    authDomain: 'bitirme-b3e7a.firebaseapp.com',
    storageBucket: 'bitirme-b3e7a.firebasestorage.app',
    measurementId: 'G-Z5SCVRBJ7S',
  );
}
